"""A module for Autocontouring CT images using TotalSegmentator."""

import argparse
import logging
import os
import sys
import time
import traceback
from typing import Dict, Union

import SimpleITK as sitk
import numpy as np
from totalsegmentator.python_api import totalsegmentator

from rt_utils import ds_helper, RTStruct
from pydicom import dcmread
from pydicom.uid import generate_uid
from pathlib import Path


def get_image_position_along_imaging_axis(ds):
    try:
        if isinstance(ds, (str, Path)):
            ds = dcmread(ds, stop_before_pixels=True)

        image_position_patient = np.array(ds.ImagePositionPatient, dtype=float)
        image_orientation_patient = np.array(ds.ImageOrientationPatient, dtype=float)
        row_cosines = image_orientation_patient[:3]
        col_cosines = image_orientation_patient[3:]
        imaging_axis = np.cross(row_cosines, col_cosines)
        return np.dot(image_position_patient, imaging_axis)

    except Exception as e:
        print(f"Could not read dataset: {e}")
        return float("inf")


def sort_by_image_position_patient(file_names_or_datasets):
    """
    Sorts DICOM image files or datasets based on their position along the imaging axis.

    This function sorts a list of DICOM file paths or datasets based on the ImagePositionPatient
    tag and the orientation of the image (using ImageOrientationPatient).

    Parameters
    ----------
    file_names_or_datasets : list of str or list of pydicom.Dataset
        The list of DICOM file paths or datasets to sort.

    Returns
    -------
    list of str or list of pydicom.Dataset
        The sorted list of DICOM file paths or datasets.

    Notes
    -----
    This function computes the imaging axis using the ImageOrientationPatient tag
    and sorts the files based on the ImagePositionPatient tag along that axis.

    Examples
    --------
    >>> sorted_files = sort_by_image_position_patient(dicom_file_list)
    >>> print(sorted_files)
    ['file1.dcm', 'file2.dcm', 'file3.dcm']
    """
    sorted_items = sorted(file_names_or_datasets, key=get_image_position_along_imaging_axis)
    return sorted_items


def load_scan(path: str):
    """Load all DICOM images in path into a list for manipulation.

    Parameters
    ----------
    path : str
        The path to a directory containing DICOM files.

    Returns
    -------
    List
        List of DICOM slices sorted according to their location on the
        patient axis from inferior to superior.
    """

    slices = [dcmread(os.path.join(path, s)) for s in os.listdir(path) if ".dcm" in s]
    slices = sort_by_image_position_patient(slices)

    # Get the slice thickness to use for mapping with RTstruct DICOM file
    slice_thickness = np.abs(
        get_image_position_along_imaging_axis(slices[0])
        - get_image_position_along_imaging_axis(slices[1])
    )

    for s in slices:
        s.SliceThickness = slice_thickness

    return slices


def get_pixels(slices: list) -> np.ndarray:
    """Extract and adjust pixel data from DICOM slices.

    Parameters
    ----------
    slices : list
        List of DICOM slices.

    Returns
    -------
    np.ndarray
        Adjusted pixel data array.
    """

    # Extract the original pixel data
    image = np.stack([s.pixel_array for s in slices]).astype(float)

    return image


class AutocontourCT:
    """A class to autocontour CT images."""

    def __init__(
        self,
        slices_path: str,
        struct_path: str,
        uid_prefix: str,
        logger: Union[logging.Logger, None],
    ) -> None:
        """Initialize the `Autocontour` class with the given parameters.

        Parameters
        ----------
        slices_path : str
            The path to the DICOM images.
        struct_path : str
            The path where RTstruct file will be written.
        uid_prefix : str
            DICOM compliant UID  prefix to use.
        logger : logging.Logger
            A logger object for logging.
        """
        self.slices_path = slices_path
        self.struct_path = struct_path
        self.uid_prefix = uid_prefix
        if logger:
            self.logger = logger
        else:
            self.logger = logging.getLogger(__name__)
            self.logger.addHandler(logging.StreamHandler())

    def load_nifti(self, path: str) -> Dict:
        """Load the nifti masks generated by `totalsegmentator`.

        Parameters
        ----------
        path : str
            The path to the nifti files

        Returns
        -------
        Dict
            A dictionary with the keys being the structures name and
            the values being the binary mask for that structure as a
            `sitk.Image`.
        """
        segs_list = os.listdir(path)
        all_masks = {}
        for segs_path in segs_list:
            # mask = nib.load(os.path.join(path, segs_path))
            mask = sitk.ReadImage(os.path.join(path, segs_path))
            mask_array = sitk.GetArrayFromImage(mask)
            if np.max(mask_array) > 0:
                all_masks[segs_path.split(".")[0]] = mask

        return all_masks

    def run(self):
        """Run the autocontour algorithm."""
        try:
            totalsegmentator(self.slices_path, self.struct_path)
        except Exception as e:
            self.logger.error(e)
            self.logger.debug(e, exc_info=True)
            sys.exit(1)

        all_contours = self.load_nifti(self.struct_path)

        # read the slices, get sitk image from it and align the masks
        slices = load_scan(self.slices_path)
        img_array = get_pixels(slices)
        origin = tuple(np.asarray(slices[0].ImagePositionPatient, dtype=float))
        iop = slices[0].ImageOrientationPatient
        row_cosines = np.asarray(iop[:3], dtype=float)
        col_cosines = np.asarray(iop[3:])
        imaging_axis = np.cross(row_cosines, col_cosines)
        direction = np.concatenate([row_cosines, col_cosines, imaging_axis]).tolist()
        spacing_z = slices[0].SliceThickness
        spacing_yx = np.asarray(slices[0].PixelSpacing, dtype=float)
        spacing = tuple(np.asarray([spacing_yx[1], spacing_yx[0], spacing_z]))

        sitk_img = sitk.GetImageFromArray(img_array)
        sitk_img.SetOrigin(origin)
        sitk_img.SetSpacing(spacing)
        sitk_img.SetDirection(direction)

        # resample the masks to image grid using nearest-neighbor
        all_masks = []
        for key, mask_img in all_contours.items():
            resampler = sitk.ResampleImageFilter()
            resampler.SetReferenceImage(sitk_img)
            resampler.SetInterpolator(sitk.sitkNearestNeighbor)
            resampler.SetOutputSpacing(sitk_img.GetSpacing())
            resampler.SetOutputOrigin(sitk_img.GetOrigin())
            resampler.SetOutputDirection(sitk_img.GetDirection())
            resampler.SetSize(sitk_img.GetSize())
            resampler.SetDefaultPixelValue(0)
            resampled_mask = resampler.Execute(mask_img)

            mask_array = sitk.GetArrayFromImage(resampled_mask)
            mask_array = np.moveaxis(mask_array, 0, -1)
            mask_array = mask_array > 0
            all_masks.append((mask_array, key))

        ds = ds_helper.create_rtstruct_dataset(slices)
        rtstruct = RTStruct(slices, ds)
        rtstruct.ds.Manufacturer = "ROSAML"
        rtstruct.ds.InstitutionName = ""
        rtstruct.ds.ManufacturerModelName = "MRPAC"
        rtstruct.frame_of_reference_uid = rtstruct.ds.ReferencedFrameOfReferenceSequence[
            -1
        ].FrameOfReferenceUID
        rtstruct.ds.SeriesDescription = "CT Auto Contours TotalSegmentator"
        rtstruct.ds.StructureSetName = "AutoContours"
        rtstruct.ds.SeriesDate = rtstruct.ds.InstanceCreationDate
        rtstruct.ds.SeriesTime = rtstruct.ds.InstanceCreationTime

        if self.uid_prefix:
            rtstruct.ds.SeriesInstanceUID = (
                self.uid_prefix + "1.2.1." + "".join(str(time.time()).split("."))
            )
            rtstruct.ds.SOPInstanceUID = (
                self.uid_prefix + "1.3.1." + "".join(str(time.time()).split("."))
            )
        else:
            rtstruct.ds.SeriesInstanceUID = generate_uid(prefix=self.uid_prefix)
            rtstruct.ds.SOPInstanceUID = generate_uid(prefix=self.uid_prefix)

        for el in all_masks:
            rtstruct.add_roi(mask=el[0], name=el[1], approximate_contours=False)

        # Save the RTStruct DICOM file
        if not os.path.exists(self.struct_path):
            os.makedirs(self.struct_path)
        RTDCM_path = os.path.join(self.struct_path, "AutoContour.dcm")
        try:
            rtstruct.ds.save_as(RTDCM_path)
            msg = (
                "Saved RTSTRUCT for "
                + str(rtstruct.ds.PatientName)
                + " "
                + str(rtstruct.ds.PatientID)
            )
            self.logger.info(msg)

        except Exception as e:
            self.logger.error(e)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto-Contour CT images using TotalSegmentator")
    parser.add_argument("Data_path", type=str, help="Path to the DICOM slices")
    parser.add_argument(
        "RTSTruct_output_path",
        type=str,
        help="Path to where to save the RTSTruct DICOM file",
    )
    parser.add_argument(
        "UID_PREFIX", type=str, help="A DICOM UID_PREFIX to use when generating UIDs"
    )
    args = parser.parse_args()

    slices_path = args.Data_path
    output_path = args.RTSTruct_output_path
    if args.UID_PREFIX != "None":
        UID_PREFIX = args.UID_PREFIX
    else:
        UID_PREFIX = None

    try:
        autocontour = AutocontourCT(slices_path, output_path, UID_PREFIX, None)
        autocontour.run()
    except Exception as e:
        print(f"{e}")
        stack_trace = traceback.format_exc()
        print(stack_trace)
